id = "please"
name = "Please"
version = "0.0.1"
description = "Language support for Please build system (plz) BUILD files"
schema_version = 1

[grammars.starlark]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-starlark"
rev = "a453dbf3ba433db0e5ec621a38a7e59d72e4dc69"
[language_servers.build-langserver]
name = "Please LSP"
languages = ["Please"]
